Action items
nokia-wroclaw/innovativeproject-retrotool pull request #31
Opened 2017-05-01 23:15 UTC by Avogardo

2017-05-02 07:09 UTC, mstanuch requested changes
Also you have an bug - start date can be after deadline.

2017-05-02 07:09 UTC, mstanuch commented on app/imports/api/actionItems/methods.js
> +            const closeMessage = '';
You can add default value for `open` and `closeMessage`.

2017-05-02 07:09 UTC, mstanuch commented on app/imports/components/ActionItems/ActionItemsBoard/ActionItem.jsx
> +        name: 'Member',
You should display that action item doesn't have assignee.

2017-05-02 07:09 UTC, mstanuch commented on app/imports/components/ActionItems/ActionItemsBoard/ActionItems.jsx
> +    handlers: PropTypes.arrayOf(
Separate Meteor from React.

2017-05-02 07:09 UTC, mstanuch commented on app/imports/components/ActionItems/ActionItemsBoard/ActionItems.jsx
> +    onData: PropTypes.func.isRequired,
Separate react-komposer from react.

2017-05-02 07:09 UTC, mstanuch commented on app/imports/components/ActionItems/ActionItemsBoard/ActionItemsToolbar.jsx
> +    const categories = [
Category isn't the best name. Maybe something with status?

2017-05-02 07:09 UTC, mstanuch commented on app/imports/components/ActionItems/ActionItemsBoard/index.js
> +            const member = Meteor.users.find(actionItem.assigneeId).fetch();
`findOne`?

2017-05-02 07:09 UTC, mstanuch commented on app/imports/components/ActionItems/ActionItemsBoard/index.js
> +            handlers,
Separate Meteor from React.

2017-05-02 07:09 UTC, mstanuch commented on app/imports/components/ActionItems/AddActionItem/CustomDatePicker.jsx
> +    <DatePicker
It's too custom. At least allow to add other props.

2017-05-02 10:39 UTC, Avogardo commented on app/imports/components/ActionItems/ActionItemsBoard/ActionItems.jsx
> +    handlers: PropTypes.arrayOf(
Meteor and composer are necessary to properly working functions in index.js with onData wrapper. Cant figure better solution

2017-05-03 18:29 UTC, mstanuch approved these changes

2017-05-03 18:29 UTC, merged