Bug reopen action item
nokia-wroclaw/innovativeproject-retrotool pull request #37
Opened 2017-05-04 20:49 UTC by Avogardo

Moderator and assigne can change action item status
There is no close message field while reopening action item

2017-05-05 20:59 UTC, mstanuch requested changes

2017-05-05 20:59 UTC, mstanuch commented on app/imports/components/ActionItems/CloseOrReopenActionItem/CloseOrReopenActionItem.jsx
> +                    <CustomTextField
It isn't required.

2017-05-05 20:59 UTC, mstanuch commented on app/imports/components/ActionItems/CloseOrReopenActionItem/CloseOrReopenActionItem.jsx
> +                        value={closeMessage}
`value={closeMessage}` overwrite your message when you want to change it, because you can't change prop in this way.

2017-05-05 21:06 UTC, mstanuch commented on app/imports/components/ActionItems/ActionItemsBoard/ActionItem.jsx
>              {text} <br /> <br />
You have three ways to do it better:
1. Use html tags, eg. `<p>`
2. Style it to get rid off `<br />`
3. Use both

2017-05-05 21:08 UTC, Avogardo commented on app/imports/components/ActionItems/CloseOrReopenActionItem/CloseOrReopenActionItem.jsx
> +                    <CustomTextField
Stock text field has no default value prop

2017-05-05 21:11 UTC, Avogardo commented on app/imports/components/ActionItems/CloseOrReopenActionItem/CloseOrReopenActionItem.jsx
> +                        value={closeMessage}
It's working fine. I can save change message also no touched message is saved thanks this prop

2017-05-05 21:13 UTC, mstanuch commented on app/imports/components/ActionItems/CloseOrReopenActionItem/CloseOrReopenActionItem.jsx
> +                    <CustomTextField
It has. Default value is provided by schema.

2017-05-05 21:15 UTC, mstanuch commented on app/imports/components/ActionItems/CloseOrReopenActionItem/CloseOrReopenActionItem.jsx
> +                        value={closeMessage}
I thought that it's the reason why you're using `CustomTextField`.

2017-05-07 13:28 UTC, mstanuch approved these changes

2017-05-07 13:28 UTC, mstanuch commented on app/imports/components/ActionItems/ActionItemsBoard/ActionItem.jsx
> +import '../Style/ActionItems.css';
You should rather write `.less` file and include it in `main.less`

2017-05-07 13:29 UTC, merged