Admin panel continue
nokia-wroclaw/innovativeproject-retrotool pull request #55
Opened 2017-05-30 21:24 UTC by mikze

2017-05-30 21:42 UTC, Avogardo commented on app/imports/components/Users/AdminPanel/AdminPanel.jsx
> +                        onTouchTap={this.changeOption}
I can jump between UsersList and ProjectsList using only one of this buttons ;p

2017-05-31 07:54 UTC, mstanuch commented on app/imports/components/Users/AdminPanel/UsersAndProjectsManagement/ProjectsList/singleProjectView/schema.js
> +        defaultValue: 'mikze',
Nice try ;)

2017-05-31 13:40 UTC, mstanuch requested changes
I reviewed a part of your changes. Before I review everything, please merge branch devel into your branch.

USE: git merge
https://git-scm.com/docs/git-merge

2017-05-31 13:40 UTC, mstanuch commented on app/imports/api/projects/actions.js
> +const removeMod = (projectId, userId) => {
Use full name `removeModerator`

2017-05-31 13:40 UTC, mstanuch commented on app/imports/components/Users/AdminPanel/UsersAndProjectsManagement/ProjectsList/ProjectsList.jsx
> +    filtr(project) {
Typo

2017-05-31 13:40 UTC, mstanuch commented on app/imports/components/Users/AdminPanel/UsersAndProjectsManagement/ProjectsList/ProjectsList.jsx
> +        this.addMode = this.addMode.bind(this);
`Mod`, `Mode` - please use full name `Moderator`.

2017-05-31 13:40 UTC, mstanuch commented on app/imports/components/Users/AdminPanel/UsersAndProjectsManagement/ProjectsList/ProjectsList.jsx
> +        this.setState({ openDialog: true });
```
this.setState({ 
    openDialog: true,
    moderators: project.moderators,
    project,
});
```

2017-05-31 13:40 UTC, mstanuch commented on app/imports/components/Users/AdminPanel/UsersAndProjectsManagement/UsersList/UsersList.jsx
> +    filtr(user) {
Typo

2017-05-31 13:40 UTC, mstanuch commented on app/imports/components/Users/AdminPanel/UsersAndProjectsManagement/ProjectsList/ProjectsList.jsx
> +            project: [],
One or more?
Project or projects?

2017-05-31 13:40 UTC, mstanuch commented on app/imports/components/Users/AdminPanel/UsersAndProjectsManagement/ProjectsList/ProjectsList.jsx
> +            moderators: [],
You can get moderators reactively.

2017-06-04 15:12 UTC, mstanuch commented
Please reopen this pull request. Select `devel` as base branch.

2017-06-04 15:12 UTC, closed without merging